apiVersion: v1
kind: Service
metadata:
  name: scope-client
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 4042
    nodePort: 4042
    protocol: TCP
    name: scope-client
  selector:
    name: scope-client-pod
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: scope-client
spec:
  replicas: 1
  selector:
    name: scope-client-pod
  template:
    metadata:
      name: scope-client-pod
      labels:
        name: scope-client-pod
    spec:
      restartPolicy: Always
      containers:
      - name: scope-client
        image: billyzhang2010/scope-client:latest
        ports:
        - containerPort: 80
        - containerPort: 4042
        imagePullPolicy: "Always"
